# TODO Spaces
#     Search Spaces
#         GET /2/spaces/search
#     Spaces lookup
#         GET /2/spaces
#         GET /2/spaces/:id
#         GET /2/spaces/:id/buyers
#         GET /2/spaces/:id/tweets
#         GET /2/spaces/by/creator_ids
