on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  documentation:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v4.1.1
      - name: Generate
        run: |
          nimble install -d -y
          nimble docs
      - name: Update Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs

